ew.apps.battery={
    state:{def:{page:1}}};

if (require('Storage').readJSON('ew.json', 1).battery) {
    ew.apps.battery.state.def = require('Storage').readJSON('ew.json', 1).battery;
    
}

//ew.UI.icon.battery="nE4whC/AHcCkQACkAbVDQYABDf4YQDyiHEAA6PODRY4PDf4b/Df4bKlwba9wb1lwba9wbb8QbYKQIbZKQIb0KQIbZDQIADDeJVJDeTDXfhAbvpxSFDaj7ZDbwGFDag2GDalCDbQAHDf4b/Df4btgQaLkAbNAH4A/AAg=";
//ew.UI.icon.battery="mEwwhC/AH4AZgMRAAUQC9USmczkIXSgEv///mIXTkYvTLgYAFC50SkQACC6REBAAcyxAXNUgMz+YXGMRgXBn4XWI5AX/C6x3XC/4X/C/4X/C/4XtmYXXmYXPCooXPgERkQAGiIWMC4IAIC5pIBAAxGNAH4A/ABI=";
//ew.UI.icon.battery="mEwwgLIgMRAAkQEZ4WFAAIXQu4AEC/4XWOo55OUgyqQgMSkQAIkIXLCxIABC5URC5ZgKC/4XOkIXWiKuEC6EhC6zqBC61BC6khigXViNOC63uC6khjwXVIwIXBSIIABC6Hu93kC6RGCAAfhJQIXNIwQADMQQXMXgIWEJIJ3OIxIXNOIZJCQAgXPJQJGDd6BiCIwYXTA4gXRIwgXSXgQXUAwgXRSIIXWIwgXSCwgXQkQuFC6IAGC/4XSgIXLiAXKRQyuEC5bqBABIXKDBYWGA";
//ew.UI.icon.battery="l0uwgjg/4ADCqEPCofzmAWVn4WmmYAGIxcDCg8znGIC5QWJmeIwAWVwYW/C1TOCFqgVDLf4W/C0IABCxMPZQQAG+cwC34W/C34W/C3HzmYABn4tSCwRb/C34WMmfwCxIXLCpQARA";
//ew.UI.icon.battery="mEwwhC/AFMBiIACiAXmCYYAHC/4X/C8UhC6sSC60fI60/C6sS+YXVj4XWn/yC6kS//xC6kfC60//8xC6ZGBC6WIAAOPC4IAB+YICC5xGBAAX4C6IABwYXBnAXTJIJGDC6ZGDC6ZGDC6M/IwgXSIwgXRIwoXRIwoXRIwoXQwZGFF6IAGC/4X/C+YA/ADI";
//ew.UI.icon.battery="mEwwkEogA/AE9AOIZuSC6ilLC/4X/C8UQC6sBC60PC60/L6sB+YXVh/yC6s/+IXUgP/C6sP//wC6k//8wC6ZGB/8gC6GIAAOPC4IAB+YICC5xGBAAX4C6IABwYXBnAXTJIJGDC6ZGDC6ZGDC6M/IwgXSIwgXRIwoXRIwoXRIwoXQwZGFF6IAGC/4X/C+YA/ADIA="
//ew.UI.icon.battery="mEwwhC/AFMIxAACwAXmCYYAHC/4X/C8UoC6uDnAXVl4vWn5fVwf/C6sv+YXVn4XVIwPyC6kv//4C6k/C6pGB/7WEC5+PC4IABPIYXOIwIACJIbXSJIgXQJILAEC6SQEC6SQEC6E/IwgXSd6uIa6oABIwoXRIwoXQwZGFF6IAGC/4X/C+YA/ADIA=";


// install icon
if (!require('Storage').read("ew_i_battery.img")) {
    let icon="mEwwhC/AFMIxAACwAXmCYYAHC/4X/C8UoC6uDnAXVl4vWn5fVwf/C6sv+YXVn4XVIwPyC6kv//4C6k/C6pGB/7WEC5+PC4IABPIYXOIwIACJIbXSJIgXQJILAEC6SQEC6SQEC6E/IwgXSd6uIa6oABIwoXRIwoXQwZGFF6IAGC/4X/C+YA/ADIA=";
    require('Storage').write("ew_i_battery.img", require("heatshrink").decompress(atob(icon)));
}