ew.apps.hr={
    state:{def:{page:0, topL:100, btmL:75}}};

if (require('Storage').readJSON('ew.json', 1).hr) {
    ew.apps.hr.state.def = require('Storage').readJSON('ew.json', 1).hr;
    
}

//ew.UI.icon.hr="n0+whC/AH4A/AH4Ae7oAB6AMIhoNCDhYPDCRIMFFpIQGD4wMMCBYxEJIw+JCBAxEBhIfGDxQfBBZQeGCJQANHiAAN4Aec7gec7nMDwgPIn89DxnMAAIeM//9DpweM6QeMLQIeO6f/+gdODxnf//zLRoeNn4eKDooeR6YiELQoeJaYf/n4aCMIIdKDwkNaYYZBTIMzDQVP/4oCDo/ADwwaB/9NAYIBBMIYeBDo4eFLoRSBeYPf+YeBppGBBAJaD6hbIDwZ1BAIXy6g5BEIIGBC4XDEgIeJKAI7CAYQ6BDwREBDYIAC+ZbIgEDBoM9HIJ0CAQIcDl4eOgEzmaTDPALeBn/0HYXzmYMBDwYdGbQi2E/phB4geBnnM4kzAYI8IDwndd4Q7BDQQ4EaxK7FAAi+B/9M5hCBDwwdIHwoABp45D4j3DHhg+G7jdBLA48MHwo1B56ZBDpA8LHwgSBagKwCHiQ+DCQQeBlg8VAAITDDwI8WAAMMCgctHi4+FHjA+GHjA+MDqQ+KHiY+KDqgfIDqxeGLSo+IDrAfEDrReCLTIA/AH4A/AFg";
//ew.UI.icon.hr="mEwwhC/AH4At7oAB6AJFhoKCCxYYGCwYYIBgoYDBJIuIEwgJJFxImCBJIuLABXcC7Q8HloWK5nAC5HT+gXJ5gXK7/zCxQXKn4XICwQXK/4XHLgIXL6n//4EBkYWHC43UFYPT+YXC/89IooXEX4XT/9N7/0C4IzBC4IWF5jXFn///sv/s/poeB/pFFC4pIB/6MBn89AIPf//0CIPE/9MIwsAh5yBOoYZCmfzDQIAB/gXGgCiCXoQXCmg4BC4oWEMATtDp89//cCgPcI4gXFYIaJBDQPz5k/MASlGGAwyCOoXfniNIGA/d4ZYDFxgwE5gXBFgouJGAbQBC4LUGFxIABCQXCOwIuPAAMMBwPNmguRAAIrGFxwwEFyYwJCxwwHFx4YGCyJJFCyQwDFyYYCCyoA/AH4AF";


// install icon
if (!require('Storage').read("ew_i_hr.img")) {
    let icon="mEwwhC/AH4At7oAB6AJFhoKCCxYYGCwYYIBgoYDBJIuIEwgJJFxImCBJIuLABXcC7Q8HloWK5nAC5HT+gXJ5gXK7/zCxQXKn4XICwQXK/4XHLgIXL6n//4EBkYWHC43UFYPT+YXC/89IooXEX4XT/9N7/0C4IzBC4IWF5jXFn///sv/s/poeB/pFFC4pIB/6MBn89AIPf//0CIPE/9MIwsAh5yBOoYZCmfzDQIAB/gXGgCiCXoQXCmg4BC4oWEMATtDp89//cCgPcI4gXFYIaJBDQPz5k/MASlGGAwyCOoXfniNIGA/d4ZYDFxgwE5gXBFgouJGAbQBC4LUGFxIABCQXCOwIuPAAMMBwPNmguRAAIrGFxwwEFyYwJCxwwHFx4YGCyJJFCyQwDFyYYCCyoA/AH4AF";
    require('Storage').write("ew_i_hr.img", require("heatshrink").decompress(atob(icon)));
}
